name       : train_sweep/baseline/
model      : teacher.pt
reg_type   : jacobian
barrier    : relu
gpu_number : "7"
seed       : 1

adv_train      : False
distill        : False
parseval_train : False
max_eig        : False
only_reg       : False
reg            : False
compute_reg    : False
plot           : False
loop           : True

# model

channels1 : 32
channels2 : 64
hidden    : 128

# data

input_shape : (1, 28, 28)
num_classes : 10

# training

epochs          : 10
batch_size      : 128
test_batch_size : 128
learning_rate   : 0.001
distill_temp    : 20

# eps_inf = 0.3 => eps_l2 = sqrt(784)*eps_inf = 28*0.3 = 8.4
# eps_inf = 0.2 => eps_l2 = 5.6
# eps_inf = 0.15 => eps_l2 = 4.2
epsilon   : 4.2
eta       : 0.03

verbose      : True
log_interval : 200
save_step    : 1

# attack

attack_type       : pgd  # gn # fgsm # pgd # deep_fool # cw
perturbation_type : linf # only for pgd
budget            : 0.15 # for gn, fgsm, pgd
alpha             : 0.01 # only for pgd
max_iter          : 40   # for pgd, deep_fool, cw
random_start      : True # only for pgd

