name       : jacobian/jac_3 # isometry/kyles_TEMP
model      : 00030.pt # baseline.pt # 00030.pt
reg_type   : jacobian # isometry # jacobian
gpu_number : None
seed       : 1

train          : False
load           : True
adv_train      : False
adv_test       : True
parseval_train : False
distill        : False
reg            : False
loop           : False
plot           : False

# model

channels1 : 32
channels2 : 64
hidden    : 128

# data

input_shape : (1, 28, 28)
num_classes : 10

# training

epochs          : 30
batch_size      : 128
test_batch_size : 128
learning_rate   : 0.001

distill_temp : 20

# eps_inf = 0.3 => eps_l2 = sqrt(784)*eps_inf = 28*0.3 = 8.4
# eps_inf = 0.2 => eps_l2 = sqrt(784)*eps_inf = 28*0.2 = 5.6
epsilon   : 5.6
eta_min   : None
eta_max   : 0.0001
epoch_reg : 1

verbose      : True
log_interval : 8
save_step    : 1

# testing

testing_batch_size : 128
test_epoch         : 30
loader             : test

# attack

attack_type       : pgd  # gn # fgsm # pgd # deep_fool # cw
perturbation_type : linf # only for pgd
budget            : 0.3  # for gn, fgsm, pgd
alpha             : 0.01 # only for pgd
max_iter          : 40   # for pgd, deep_fool, cw
random_start      : True # only for pgd

