name  : isometry/iso-4_1 # isometry/kyles_TEMP
model : 00030.pt # baseline.pt # 00030.pt
reg_type : isometry # isometry # jacobian
gpu_number : None
seed  : 1

train      : True
load       : False
adv_train  : False
adv_test   : False
distill    : False
reg        : True

# model

channels1 : 32
channels2 : 64
hidden    : 128

# data

input_shape : (1, 28, 28)
num_classes : 10

# training

epochs          : 30
batch_size      : 64
test_batch_size : 64
learning_rate   : 0.001

distill_temp : 20

# eps_inf = 0.3 => eps_l2 = sqrt(784)*eps_inf = 28*0.3 = 8.4
# eps_inf = 0.2 => eps_l2 = sqrt(784)*eps_inf = 28*0.2 = 5.6
epsilon   : 5.6
eta_min   : None
eta_max   : 0.0001
epoch_reg : 1

verbose      : True
log_interval : 200
save_step    : 1

# testing

testing_batch_size : 128
test_epoch         : 30
loader             : test

# attack

attack_type       : pgd # fgsm # gn # pgd # deep_fool # cw
std               : 0.1
perturbation_type : linf # pgd only does Linf, deep_fool only does L2
budget            : 0.2
alpha             : 0.01
max_iter          : 40
random_start      : True

