name  : kyles_TEMP # iso_6
model : distilled_from_baseline.pt # baseline.pt # adv_train.pt
gpu_number  : "5"
seed  : 1

train       : False
load        : True
adv_train   : False
adv_test    : True
reg         : False

# model

channels1 : 32
channels2 : 64
hidden    : 128

# data

input_shape : (1, 28, 28)
num_classes : 10

# training

epochs          : 10
batch_size      : 32
test_batch_size : 125
learning_rate   : 0.01

distill : True
distill_temp : 20

# eps_inf = 0.3 => eps_l2 = sqrt(784)*eps_inf = 28*0.3 = 8.4
epsilon_l2 : 10
lambda_min : 0.00001
lambda_max : 0.0001

verbose       : True
log_interval  : 100
save_step     : 1

# testing

testing_batch_size  : 128
test_epoch          : 30
loader              : test

# attack

attack_type       : fgsm # deep_fool # cw
perturbation_type : linf # deep_fool only does L2
budget            : 0.1
alpha             : 0.01
max_iter          : 40

