name  : kyles_TEMP # iso_6 # vanilla | iso_1 | iso_2 | iso_3 | iso_4 | iso_5 | iso_6
model : 00010.pt # baseline.pt # adv_train.pt
seed  : 1

train       : False
gpu_number  : "5"
load        : True
adv_train   : False
adv_test    : True
reg         : False
jacobian    : False

# model

channels1 : 32
channels2 : 64
hidden    : 128

# data

input_shape : (1, 28, 28)
num_classes : 10

# training

epochs          : 10
batch_size      : 32
test_batch_size : 125
learning_rate   : 0.01

# e.g., eps_inf = 0.3 => eps_l2 = sqrt(784)*eps_inf = 28*0.3 = 8.4
epsilon_l2 : 10
lambda_min : 0.00001
lambda_max : 0.0001

verbose       : True
log_interval  : 100
save_step     : 1

# testing

testing_batch_size  : 128
test_epoch          : 30
loader              : test

# attack
attack_type       : deep_fool # fgsm #  cw # 
perturbation_type : linf # deep_fool only does L2
budget            : 0.1
alpha             : 0.01
max_iter          : 40

