name       : jacobian/test  # isometry/kyles_TEMP
model      : adv_train_1_10.pt       # baseline.pt # 00030.pt # isometry_defense.pt
reg_type   : jacobian       # isometry # jacobian
barrier    : relu
gpu_number : None
seed       : 1

adv_test       : True
reg            : False
compute_reg    : False
plot           : False
test_bound     : False

# WandB settings

wandb_project_name  : MNIST Attacks
run_sweep           : True

# model

channels1 : 32
channels2 : 64
hidden    : 128

# data

input_shape : (1, 28, 28)
num_classes : 10

# testing

testing_batch_size : 128
loader             : test

# eps_inf = 0.3 => eps_l2 = sqrt(784)*eps_inf = 28*0.3 = 8.4
# eps_inf = 0.2 => eps_l2 = 5.6
# eps_inf = 0.15 => eps_l2 = 4.2
epsilon : 4.2
eta     : 0.03

verbose      : True
log_interval : 30

# attack

attack_type       : pgd  # gn # fgsm # pgd # deep_fool # cw
perturbation_type : linf # only for pgd
budget            : 0.15  # for gn, fgsm, pgd
alpha             : 0.01 # only for pgd
max_iter          : 40   # for pgd, deep_fool, cw
random_start      : True # only for pgd
save_an_image     : False

